[build]
builder = "dockerfile"
dockerfilePath = "backend/Dockerfile"
context = "backend"

[deploy]
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
# railway will automatically use the PORT env var for the backend
